services:
  spotin:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPOT_IN_DATABASE_URL=postgresql://${SPOT_IN_DATABASE_USER}:${SPOT_IN_DATABASE_PASSWORD}@postgres:5432/${SPOT_IN_DATABASE_NAME}

  postgres:
    container_name: spotin-postgres
    image: postgres:${POSTGRES_IMAGE_VERSION:-latest}
    restart: unless-stopped
    env_file:
      - postgres.env
    networks:
      - spotin_network
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3
